### ISSUE TITLE
-offtopic ungoogled-chromium win

### ISSUE THREAD

**Issue by rubyando** [tangalbert919/ungoogled-chromium-freebsd#1]
Hi @tangalbert919 sorry for asking unrelated question didn't find any contact info on your profile,

wanted to know if you're gonna release U-C builds for windows ever again? the last one you did was version 89.0.4389.114

thanks

**Comment by tangalbert919** [comment]
Someone else already does that now, so I don't think I need to release U-C builds there anymore.
